MUTATION_PROBABILITY = 0.01
REPRODUCTION_RATE = 0.2
POPULATION_SIZE = 1000
ENCODING_TYPE = library.AlphabeticEncoding
FITNESS_TYPE = library.WinPlayedFitness

# Alphabetic settings
ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ "
MAX_ALPHABETIC_INDIVIDUAL_INIT_LENGTH = 10
