ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ "
MUTATION_PROBABILITY = 0.01
REPRODUCTION_RATE = 0.2
POPULATION_SIZE = 1000
INDIVIDUAL_TYPE = "AlphabeticIndividual"
MAX_ALPHABETIC_INDIVIDUAL_INIT_LENGTH = 10
